//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.12 at 07:19:40 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.h2sm.com/testtask/objects", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.h2sm.testtask.objects;
